name: iraq_emis
description: A new Flutter project for Iraq EMIS System.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2
  
  # مكتبة الاتصال بالسيرفر وجلب البيانات
  http: ^1.1.0
  
  # مكتبة متصفح الويب لتسجيل الدخول
  webview_flutter: ^4.4.2
  
  # مكتبة تشغيل الصوتيات
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # مسارات الصور والملفات الصوتية
  assets:
    - assets/images/avatar.jpg
    - assets/relax.mp3
