import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class DeactivatedStudentsScreen extends StatefulWidget{final String token;final String schoolId;const DeactivatedStudentsScreen({super.key,required this.token,required this.schoolId});@override State<DeactivatedStudentsScreen> createState()=>_DeactivatedStudentsScreenState();}
class _DeactivatedStudentsScreenState extends State<DeactivatedStudentsScreen>{List<Map<String,dynamic>> students=[];bool loading=true;String q='';String? error;Map<String,String> get h=>{'Authorization':widget.token,'Accept':'application/json','Content-Type':'application/json'};
@override void initState(){super.initState();load();}
Future<void> load()async{setState(()=>loading=true);final candidates=['/student/getdeactivatedstudents?schoolId=${widget.schoolId}','/student/getdeactivatedstudents?entityId=${widget.schoolId}','/student/getstudents?schoolId=${widget.schoolId}&entityId=${widget.schoolId}&isActive=false'];String? e;for(final p in candidates){try{final r=await http.get(Uri.parse('https://emis.moedu.gov.iq/api$p'),headers:h);if(r.statusCode==200){final d=jsonDecode(utf8.decode(r.bodyBytes));final x=d is Map&&d['data'] is List?d['data']:d is List?d:[];students=x.whereType<Map>().map((z)=>Map<String,dynamic>.from(z)).toList();error=null;setState(()=>loading=false);return;}e='HTTP ${r.statusCode}: ${r.body}';if(r.statusCode!=404)break;}catch(ex){e='$ex';}}if(mounted)setState((){loading=false;error=e??'تعذر تحميل الطلبة غير المفعلين';});}
String name(Map<String,dynamic>s){final f=s['fullName']??s['studentName'];if('$f'.trim().isNotEmpty)return '$f';return [s['name'],s['fatherName'],s['grandFatherName'],s['surName']].where((x)=>x!=null&&'$x'.trim().isNotEmpty).join(' ');}
Future<void> _activateStudent(Map<String,dynamic>s)async{final id=s['id'];if(id==null)return;final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('تفعيل الطالب'),content:Text('هل تريد تفعيل الطالب ${name(s)}؟'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('تفعيل'))]));if(ok!=true)return;String? e;for(final p in ['/student/activate/$id','/student/activatestudent/$id']){try{final r=await http.post(Uri.parse('https://emis.moedu.gov.iq/api$p'),headers:h);if(r.statusCode>=200&&r.statusCode<300){if(mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم تفعيل الطالب بنجاح'),backgroundColor:Colors.green));load();}return;}e='HTTP ${r.statusCode}: ${r.body}';if(r.statusCode!=404)break;}catch(ex){e='$ex';}}if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('فشل تفعيل الطالب: $e'),backgroundColor:Colors.red));}
@override Widget build(BuildContext context){final list=students.where((s)=>q.trim().isEmpty||name(s).toLowerCase().contains(q.trim().toLowerCase())||'${s['id']}'.contains(q.trim())).toList();return Scaffold(appBar:AppBar(title:const Text('الطلبة غير المفعلين',style:TextStyle(color:Colors.white)),backgroundColor:Colors.redAccent,iconTheme:const IconThemeData(color:Colors.white),actions:[IconButton(onPressed:loading?null:load,icon:const Icon(Icons.refresh,color:Colors.white))]),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[TextField(onChanged:(v)=>setState(()=>q=v),decoration:const InputDecoration(hintText:'ابحث باسم الطالب أو الرقم',prefixIcon:Icon(Icons.search),border:OutlineInputBorder())),const SizedBox(height:14),if(error!=null)Text(error!,style:const TextStyle(color:Colors.red)),if(loading)const Padding(padding:EdgeInsets.all(40),child:Center(child:CircularProgressIndicator())),if(!loading&&list.isEmpty)const Padding(padding:EdgeInsets.all(40),child:Center(child:Text('لا توجد طلبة غير مفعّلين'))),...list.map((s)=>Card(child:ListTile(title:Text(name(s),textDirection:TextDirection.rtl),subtitle:Text('رقم الطالب: ${s['id']??''}'),leading:const Icon(Icons.person_off,color:Colors.redAccent),trailing:IconButton(onPressed:()=>_activateStudent(s),icon:const Icon(Icons.person_add_alt_1,color:Colors.green),tooltip:'تفعيل الطالب'))))])));}
}
